version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: book_service
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PORT_APP}:${PORT_APP}"

volumes:
  postgres_data:
